# Generated by Django 5.2.3 on 2025-06-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_candidatescore_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exam",
            old_name="is_published",
            new_name="is_active",
        ),
        migrations.AddField(
            model_name="exam",
            name="open_duration_hours",
            field=models.PositiveIntegerField(default=12),
        ),
    ]
