# Generated by Django 5.2.3 on 2025-06-18 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_candidatescore_submitted_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidatescore",
            options={"ordering": ["-date_taken"]},
        ),
        migrations.RenameField(
            model_name="candidatescore",
            old_name="date_created",
            new_name="date_taken",
        ),
        migrations.AlterField(
            model_name="candidatescore",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scores",
                to="api.candidate",
            ),
        ),
        migrations.AlterField(
            model_name="candidatescore",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.staff",
            ),
        ),
    ]
