# Generated by Django 5.2.3 on 2025-06-26 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_is_published_exam_is_active_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="description",
            new_name="text",
        ),
        migrations.RemoveField(
            model_name="question",
            name="answer",
        ),
        migrations.AddField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(
                choices=[
                    ("A", "Option A"),
                    ("B", "Option B"),
                    ("C", "Option C"),
                    ("D", "Option D"),
                ],
                default="a",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="option_a",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="question",
            name="option_b",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="question",
            name="option_c",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="question",
            name="option_d",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="candidatescore",
            name="score",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.CreateModel(
            name="CandidateAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_option",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "Option A"),
                            ("B", "Option B"),
                            ("C", "Option C"),
                            ("D", "Option D"),
                        ],
                        default="",
                        max_length=1,
                    ),
                ),
                ("answered_at", models.DateField(auto_now=True)),
                (
                    "candidate_score",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="api.candidatescore",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.question"
                    ),
                ),
            ],
            options={
                "unique_together": {("candidate_score", "question")},
            },
        ),
    ]
