# Generated by Django 5.2.3 on 2025-06-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_description_question_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatescore",
            name="auto_score",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
