# Generated by Django 5.2.3 on 2025-06-29 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_candidatescore_auto_score"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exam",
            old_name="duration_minutes",
            new_name="countdown_minutes",
        ),
    ]
