# Generated by Django 5.2.3 on 2025-06-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_duration_minutes_exam_countdown_minutes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
