# Generated by Django 5.2.4 on 2025-07-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_candidate_id_card_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatescore",
            name="score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
