# Generated by Django 5.2.4 on 2025-07-07 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_sitesetting"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="candidateanswer",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="candidateanswer",
            name="answered_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="candidateanswer",
            name="selected_option",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "Option A"),
                    ("B", "Option B"),
                    ("C", "Option C"),
                    ("D", "Option D"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="candidatescore",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scores",
                to="api.exam",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidateanswer",
            constraint=models.UniqueConstraint(
                fields=("candidate_score", "question"),
                name="unique_answer_per_candidate_score",
            ),
        ),
    ]
