# Generated by Django 5.2.4 on 2025-07-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_candidateanswer_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SiteSetting",
            new_name="FeatureFlag",
        ),
    ]
